version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: agileboard_password
      MYSQL_DATABASE: agileboard_db
      MYSQL_USER: agileboard
      MYSQL_PASSWORD: SANT123@OSh#
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: